### ISSUE TITLE
cookie怎么填呀

### ISSUE THREAD

**Issue by 744287383** [yyzhou94/Heytapcheckin#1]
不知道格式怎么样

**Comment by yyzhou94** [comment]
在config.json内填写，text部分可以无视，样例如下：

{
  "login": [
    {
      "cookies": "source_type=XXX;sa_distinct_id=XXXXXXXXXXXXXXXXX;s_channel=XXX;s_version=XXX;app_utm=XXX"
      "User-Agent": "Mozilla/5.0 XXX"
      "if_draw": false,
      "text": "XXXX"
    }
  ],
  "enterpriseWechat": {
    "id": "XXXXXX",
    "agentld": 100000X,
    "secret": "XXXXX",
    "thumb_media_id": "XXXXX",
    "text": "XXXXX"
  },
  "pushplusToken": ""
}
