### ISSUE TITLE
大佬，把其它几个APP的打卡也一起做了吧？

### ISSUE THREAD

**Issue by nnkn** [yyzhou94/Heytapcheckin#2]
大佬，把其它几个APP的打卡也一起做了吧？

**Comment by yyzhou94** [comment]
其他APP的签到可以参考这个项目：
https://github.com/Sitoi/dailycheckin

**Comment by nnkn** [comment]
> 其他APP的签到可以参考这个项目：
> https://github.com/Sitoi/dailycheckin

额，我指的是OPPO全家桶的那几个APP，貌似那边没有？
