### ISSUE TITLE
添加积分大作战

### ISSUE THREAD

**Issue by BlueHtml** [yyzhou94/Heytapcheckin#4]
你好，请问能添加积分大作战吗？
可以参考一下这个项目：<https://github.com/Mashiro2000/HeyTapTask>，`BattleForHeyTap.py`，`BattleForRealMe.py`

**Comment by yyzhou94** [comment]
> 你好，请问能添加积分大作战吗？ 可以参考一下这个项目：https://github.com/Mashiro2000/HeyTapTask，`BattleForHeyTap.py`，`BattleForRealMe.py`

项目已更新，同时更新act_list和index两个文件

**Comment by BlueHtml** [comment]
谢谢，现在运行正常
