### ISSUE TITLE
抽奖报错

### ISSUE THREAD

**Issue by BlueHtml** [yyzhou94/Heytapcheckin#5]
你好，我把`if_draw`设置为了`true`，开启了抽奖，可是在运行时报错：
```
【赚积分-任务】
【执行任务和抽奖】: 错误，原因为: Expecting value: line 1 column 1 (char 0)
```
能帮忙看下是什么原因吗？

**Comment by yyzhou94** [comment]
> 你好，我把`if_draw`设置为了`true`，开启了抽奖，可是在运行时报错：
> 
> ```
> 【赚积分-任务】
> 【执行任务和抽奖】: 错误，原因为: Expecting value: line 1 column 1 (char 0)
> ```
> 
> 能帮忙看下是什么原因吗？

即使脚本可以运行抽奖，目前也出现了大量抽奖始终无法获取积分的情况，建议采取手动抽奖

**Comment by BlueHtml** [comment]
好的，谢谢，已经关闭抽奖
